# Generated by Django 3.2.6 on 2022-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.CharField(default='default.jpg', max_length=120),
        ),
    ]
