# Generated by Django 3.2.6 on 2022-02-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.CharField(default='default.png', max_length=120)),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('code', models.CharField(default='', max_length=120)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='', max_length=120)),
                ('sub_category', models.CharField(default='', max_length=120)),
                ('sub_category_type', models.CharField(default='', max_length=120)),
                ('warrenty', models.CharField(default='', max_length=120)),
                ('made', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
