# Generated by Django 3.2.6 on 2022-02-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daybook', '0001_initial'),
        ('daybook_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook_line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('daybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daybook.daybook')),
                ('daybook_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='daybook_type.daybook_type')),
            ],
        ),
    ]
