# Generated by Django 3.2.6 on 2022-02-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('daybook_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook_line',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partner.partner'),
        ),
    ]
