# Generated by Django 3.2.6 on 2022-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
    ]
