# Generated by Django 3.2.6 on 2022-02-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daybook_line', '0001_initial'),
        ('daybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='daybook_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daybook_line.daybook_line'),
        ),
    ]
